clear; clc;
length_sim = 2160*2;
%length_sim = 2160*2*3;
load parameters.mat;

E_max = 0;

palette = [0 0 0; 1 0 0; 0 1 0; 0 0 1; 1 1 0; 0 1 1; 1 0 1; 0.6 0.3 0; 0.4 0 0.2];

%load Results_20_21_50.mat;
load Results_20_221_250.mat;
%load Results_20_1_90.mat;
%load Results_20_151_240.mat;
en_const_0 = results{2}(:,3);
fang_const_0 = results{2}(:,4);
%perf_const_0 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 121240, length_sim, 0, E_max);
%perf_const_0 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 1120, length_sim, 0, E_max);
perf_const_0 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 201230, length_sim, 0, E_max);
%perf_const_0 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 130, length_sim, 0, E_max);
[dayen_const_0, ~] = convert_to_daily(en_const_0, start_hour, end_hour, timesteps, length_sim);
dayfang_const_0 = convert_to_daily(fang_const_0, start_hour, end_hour, timesteps, length_sim);
dayperf_const_0 = convert_to_daily(perf_const_0, start_hour, end_hour, timesteps, length_sim);

%load Results_21_21_50.mat;
load Results_21_221_250.mat;
%load Results_21_1_90.mat;
%load Results_21_151_240.mat;
en_const_1 = results{2}(:,3);
fang_const_1 = results{2}(:,4);
%perf_const_1 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 121240, length_sim, 1, E_max);
%perf_const_1 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 1120, length_sim, 1, E_max);
perf_const_1 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 201230, length_sim, 1, E_max);
%perf_const_1 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 130, length_sim, 1, E_max);
[dayen_const_1, ~] = convert_to_daily(en_const_1, start_hour, end_hour, timesteps, length_sim);
dayfang_const_1 = convert_to_daily(fang_const_1, start_hour, end_hour, timesteps, length_sim);
dayperf_const_1 = convert_to_daily(perf_const_1, start_hour, end_hour, timesteps, length_sim);

%load Results_22_21_50.mat;
load Results_22_221_250.mat;
%load Results_22_1_90.mat;
%load Results_22_151_240.mat;
en_const_2 = results{2}(:,3);
fang_const_2 = results{2}(:,4);
%perf_const_2 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 121240, length_sim, 2, E_max);
%perf_const_2 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 1120, length_sim, 2, E_max);
perf_const_2 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 201230, length_sim, 2, E_max);
%perf_const_2 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 130, length_sim, 2, E_max);
[dayen_const_2, dayz] = convert_to_daily(en_const_2, start_hour, end_hour, timesteps, length_sim);
dayfang_const_2 = convert_to_daily(fang_const_2, start_hour, end_hour, timesteps, length_sim);
dayperf_const_2 = convert_to_daily(perf_const_2, start_hour, end_hour, timesteps, length_sim);

%load Results_23_21_50.mat;
load Results_23_221_250.mat;
%load Results_23_151_240.mat;
%load Results_23_1_90.mat;
en_const_3 = results{2}(:,3);
fang_const_3 = results{2}(:,4);
%perf_const_3 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 1120, length_sim, 3, E_max);
%perf_const_3 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 121240, length_sim, 3, E_max);
perf_const_3 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 201230, length_sim, 3, E_max);
%perf_const_3 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 130, length_sim, 3, E_max);
[dayen_const_3, dayz] = convert_to_daily(en_const_3, start_hour, end_hour, timesteps, length_sim);
dayfang_const_3 = convert_to_daily(fang_const_3, start_hour, end_hour, timesteps, length_sim);
dayperf_const_3 = convert_to_daily(perf_const_3, start_hour, end_hour, timesteps, length_sim);

%load Results_24_21_50.mat;
%load Results_24_151_240.mat;
%load Results_24_1_90.mat;
%load Results_24_1_60.mat;
load Results_24_221_250.mat;
en_const_4 = results{2}(:,3);
fang_const_4 = results{2}(:,4);
%perf_const_4 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 1120, length_sim, 4, E_max);
%perf_const_4 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 121240, length_sim, 4, E_max);
perf_const_4 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 201230, length_sim, 4, E_max);
%perf_const_4 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 130, length_sim, 4, E_max);
%perf_const_4 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 160, length_sim, 4, E_max);
[dayen_const_4, dayz] = convert_to_daily(en_const_4, start_hour, end_hour, timesteps, length_sim);
dayfang_const_4 = convert_to_daily(fang_const_4, start_hour, end_hour, timesteps, length_sim);
dayperf_const_4 = convert_to_daily(perf_const_4, start_hour, end_hour, timesteps, length_sim);

%load Results_25_21_50.mat;
load Results_25_221_250.mat;
%load Results_25_151_240.mat;
%load Results_25_1_90.mat;
en_const_5 = results{2}(:,3);
fang_const_5 = results{2}(:,4);
%perf_const_5 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 1120, length_sim, 5, E_max);
%perf_const_5 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 121240, length_sim, 5, E_max);
perf_const_5 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 201230, length_sim, 5, E_max);
%perf_const_5 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 130, length_sim, 5, E_max);
[dayen_const_5, dayz] = convert_to_daily(en_const_5, start_hour, end_hour, timesteps, length_sim);
dayfang_const_5 = convert_to_daily(fang_const_5, start_hour, end_hour, timesteps, length_sim);
dayperf_const_5 = convert_to_daily(perf_const_5, start_hour, end_hour, timesteps, length_sim);

%load Results_26_21_50.mat;
load Results_26_221_250.mat;
%load Results_26_1_90.mat;
%load Results_26_151_240.mat;
en_const_6 = results{2}(:,3);
fang_const_6 = results{2}(:,4);
%perf_const_6 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 1120, length_sim, 6, E_max);
%perf_const_6 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 121240, length_sim, 6, E_max);
perf_const_6 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 201230, length_sim, 6, E_max);
%perf_const_6 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 130, length_sim, 6, E_max);
[dayen_const_6, dayz] = convert_to_daily(en_const_6, start_hour, end_hour, timesteps, length_sim);
dayfang_const_6 = convert_to_daily(fang_const_6, start_hour, end_hour, timesteps, length_sim);
dayperf_const_6 = convert_to_daily(perf_const_6, start_hour, end_hour, timesteps, length_sim);

%load Results_27_21_50.mat;
load Results_27_221_250.mat;
%load Results_27_1_90.mat;
%load Results_27_151_240.mat;
en_const_7 = results{2}(:,3);
fang_const_7 = results{2}(:,4);
%perf_const_7 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 121240, length_sim, 7, E_max);
%perf_const_7 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 1120, length_sim, 7, E_max);
perf_const_7 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 201230, length_sim, 7, E_max);
%perf_const_7 = get_my_scores(trade_off, start_hour, end_hour, timesteps, 130, length_sim, 7, E_max);
[dayen_const_7, ~] = convert_to_daily(en_const_7, start_hour, end_hour, timesteps, length_sim);
dayfang_const_7 = convert_to_daily(fang_const_7, start_hour, end_hour, timesteps, length_sim);
dayperf_const_7 = convert_to_daily(perf_const_7, start_hour, end_hour, timesteps, length_sim);

load Results.mat;
zone1 = results{2};
hourscale = 0:1/timesteps:length(controlTotal)/timesteps;
hourscale = hourscale (1:length(hourscale)-1);
%==========================================================================
%Total Results follow.

roomtemp = zone1(:,1);
roomfang = zone1(:,4);
roomeng = zone1(:,3);
roomcont = controlTotal(:,1);

perf_nfq = get_my_scores(trade_off, start_hour, end_hour, timesteps, 0, length_sim, 0, E_max);

dayen_nfq = convert_to_daily(roomeng, start_hour, end_hour, timesteps, length_sim);
dayfang_nfq = convert_to_daily(roomfang, start_hour, end_hour, timesteps, length_sim);
dayperf_nfq = convert_to_daily(perf_nfq, start_hour, end_hour, timesteps, length_sim);

figure;
subplot(2,1,1);
plot(hourscale, roomtemp); hold on;
plot(hourscale, weather_file(:,1));
ylabel('Temperature');
xlabel('Simulation Hours');
subplot(2,1,2);
plot(hourscale, roomfang);
ylabel('PMV');
xlabel('Simulation Hours');
figure;
plot(hourscale, roomfang, 'k', 'Linewidth', 1.5);
hold on; plot(hourscale, fang_const_0, 'Color', palette(2,:));
hold on; plot(hourscale, fang_const_1, 'Color', palette(3,:));
hold on; plot(hourscale, fang_const_2, 'Color', palette(4,:));
hold on; plot(hourscale, fang_const_3, 'Color', palette(5,:));
hold on; plot(hourscale, fang_const_4, 'Color', palette(6,:));
hold on; plot(hourscale, fang_const_5, 'Color', palette(7,:));
hold on; plot(hourscale, fang_const_6, 'Color', palette(8,:));
hold on; plot(hourscale, fang_const_7, 'Color', palette(9,:));
title('Thermal Comfort Comparison');
ylabel('PMV');
xlabel('Simulation Hours');
legend('Proposed','RBC 20','RBC 21','RBC 22','RBC 23','RBC 24','RBC 25','RBC 26','RBC 27');

toten_nfq = sum(roomeng);
toten_const_0 = sum(en_const_0);
toten_const_1 = sum(en_const_1);
toten_const_2 = sum(en_const_2);
toten_const_3 = sum(en_const_3);
toten_const_4 = sum(en_const_4);
toten_const_5 = sum(en_const_5);
toten_const_6 = sum(en_const_6);
toten_const_7 = sum(en_const_7);

[me, se] = father_of_accuracy(dayen_nfq);
[me_0, se_0] = father_of_accuracy(dayen_const_0);
[me_1, se_1] = father_of_accuracy(dayen_const_1);
[me_2, se_2] = father_of_accuracy(dayen_const_2);
[me_3, se_3] = father_of_accuracy(dayen_const_3);
[me_4, se_4] = father_of_accuracy(dayen_const_4);
[me_5, se_5] = father_of_accuracy(dayen_const_5);
[me_6, se_6] = father_of_accuracy(dayen_const_6);
[me_7, se_7] = father_of_accuracy(dayen_const_7);

[mf, sf] = father_of_accuracy(dayfang_nfq);
[mf_0, sf_0] = father_of_accuracy(dayfang_const_0);
[mf_1, sf_1] = father_of_accuracy(dayfang_const_1);
[mf_2, sf_2] = father_of_accuracy(dayfang_const_2);
[mf_3, sf_3] = father_of_accuracy(dayfang_const_3);
[mf_4, sf_4] = father_of_accuracy(dayfang_const_4);
[mf_5, sf_5] = father_of_accuracy(dayfang_const_5);
[mf_6, sf_6] = father_of_accuracy(dayfang_const_6);
[mf_7, sf_7] = father_of_accuracy(dayfang_const_7);
figure;
plot(hourscale, roomeng, 'k', 'Linewidth', 1.5);
hold on; plot(hourscale, en_const_0, 'Color', palette(2,:));
hold on; plot(hourscale, en_const_1, 'Color', palette(3,:));
hold on; plot(hourscale, en_const_2, 'Color', palette(4,:));
hold on; plot(hourscale, en_const_3, 'Color', palette(5,:));
hold on; plot(hourscale, en_const_4, 'Color', palette(6,:));
hold on; plot(hourscale, en_const_5, 'Color', palette(7,:));
hold on; plot(hourscale, en_const_6, 'Color', palette(8,:));
hold on; plot(hourscale, en_const_7, 'Color', palette(9,:));
title('Consumption Comparison');
legend('Proposed','RBC 20','RBC 21','RBC 22','RBC 23','RBC 24','RBC 25','RBC 26','RBC 27');
ylabel('Energy');
xlabel('Simulation Hours');

figure;
plot(perf_nfq, 'k', 'Linewidth', 1.5);
hold on; plot(perf_const_0, 'Color', palette(2,:));
hold on; plot(perf_const_1, 'Color', palette(3,:));
hold on; plot(perf_const_2, 'Color', palette(4,:));
hold on; plot(perf_const_3, 'Color', palette(5,:));
hold on; plot(perf_const_4, 'Color', palette(6,:));
hold on; plot(perf_const_5, 'Color', palette(7,:));
hold on; plot(perf_const_6, 'Color', palette(8,:));
hold on; plot(perf_const_7, 'Color', palette(9,:));
legend('Proposed','RBC 20','RBC 21','RBC 22','RBC 23','RBC 24','RBC 25','RBC 26','RBC 27');
title('Performance Comparison');
ylabel('Total Score');
xlabel('Control Steps');

figure;
plot(dayz, dayperf_nfq, 'k', 'Linewidth', 1.5);
hold on; plot(dayz, dayperf_const_0, 'Color', palette(2,:));
hold on; plot(dayz, dayperf_const_1, 'Color', palette(3,:));
hold on; plot(dayz, dayperf_const_2, 'Color', palette(4,:));
hold on; plot(dayz, dayperf_const_3, 'Color', palette(5,:));
hold on; plot(dayz, dayperf_const_4, 'Color', palette(6,:));
hold on; plot(dayz, dayperf_const_5, 'Color', palette(7,:));
hold on; plot(dayz, dayperf_const_6, 'Color', palette(8,:));
hold on; plot(dayz, dayperf_const_7, 'Color', palette(9,:));
legend('Proposed','RBC 20','RBC 21','RBC 22','RBC 23','RBC 24','RBC 25','RBC 26','RBC 27');
title('Daily Performance Comparison');
ylabel('Total Score');
xlabel('Day');
figure;
plot(dayz, dayen_nfq, 'k', 'Linewidth', 1.5);
hold on; plot(dayz, dayen_const_0, 'Color', palette(2,:));
hold on; plot(dayz, dayen_const_1, 'Color', palette(3,:));
hold on; plot(dayz, dayen_const_2, 'Color', palette(4,:));
hold on; plot(dayz, dayen_const_3, 'Color', palette(5,:));
hold on; plot(dayz, dayen_const_4, 'Color', palette(6,:));
hold on; plot(dayz, dayen_const_5, 'Color', palette(7,:));
hold on; plot(dayz, dayen_const_6, 'Color', palette(8,:));
hold on; plot(dayz, dayen_const_7, 'Color', palette(9,:));
legend('Proposed','RBC 20','RBC 21','RBC 22','RBC 23','RBC 24','RBC 25','RBC 26','RBC 27');
title('Daily Consumption Comparison');
ylabel('Energy');
xlabel('Day');

figure;
subplot(2,1,1);
plot(dayz, me, 'k', 'Linewidth', 1.5);
hold on; plot(dayz, me_0, 'Color', palette(2,:));
hold on; plot(dayz, me_1, 'Color', palette(3,:));
hold on; plot(dayz, me_2, 'Color', palette(4,:));
hold on; plot(dayz, me_3, 'Color', palette(5,:));
hold on; plot(dayz, me_4, 'Color', palette(6,:));
hold on; plot(dayz, me_5, 'Color', palette(7,:));
hold on; plot(dayz, me_6, 'Color', palette(8,:));
hold on; plot(dayz, me_7, 'Color', palette(9,:));
legend('Proposed','RBC 20','RBC 21','RBC 22','RBC 23','RBC 24','RBC 25','RBC 26','RBC 27');
ylabel('Mean value');
title('Energy daily statistics');
subplot(2,1,2);
plot(dayz, se, 'k', 'Linewidth', 1.5);
hold on; plot(dayz, se_0, 'Color', palette(2,:));
hold on; plot(dayz, se_1, 'Color', palette(3,:));
hold on; plot(dayz, se_2, 'Color', palette(4,:));
hold on; plot(dayz, se_3, 'Color', palette(5,:));
hold on; plot(dayz, se_4, 'Color', palette(6,:));
hold on; plot(dayz, se_5, 'Color', palette(7,:));
hold on; plot(dayz, se_6, 'Color', palette(8,:));
hold on; plot(dayz, se_7, 'Color', palette(9,:));
legend('Proposed','RBC 20','RBC 21','RBC 22','RBC 23','RBC 24','RBC 25','RBC 26','RBC 27');
ylabel('Standard deviation');
xlabel('Day');

figure;
subplot(2,1,1);
plot(dayz, mf, 'k', 'Linewidth', 1.5);
hold on; plot(dayz, mf_0, 'Color', palette(2,:));
hold on; plot(dayz, mf_1, 'Color', palette(3,:));
hold on; plot(dayz, mf_2, 'Color', palette(4,:));
hold on; plot(dayz, mf_3, 'Color', palette(5,:));
hold on; plot(dayz, mf_4, 'Color', palette(6,:));
hold on; plot(dayz, mf_5, 'Color', palette(7,:));
hold on; plot(dayz, mf_6, 'Color', palette(8,:));
hold on; plot(dayz, mf_7, 'Color', palette(9,:));
legend('Proposed','RBC 20','RBC 21','RBC 22','RBC 23','RBC 24','RBC 25','RBC 26','RBC 27');
ylabel('Mean value');
title('Fanger score daily statistics');
subplot(2,1,2);
plot(dayz, sf, 'k', 'Linewidth', 1.5);
hold on; plot(dayz, sf_0, 'Color', palette(2,:));
hold on; plot(dayz, sf_1, 'Color', palette(3,:));
hold on; plot(dayz, sf_2, 'Color', palette(4,:));
hold on; plot(dayz, sf_3, 'Color', palette(5,:));
hold on; plot(dayz, sf_4, 'Color', palette(6,:));
hold on; plot(dayz, sf_5, 'Color', palette(7,:));
hold on; plot(dayz, sf_6, 'Color', palette(8,:));
hold on; plot(dayz, sf_7, 'Color', palette(9,:));
legend('Proposed','RBC 20','RBC 21','RBC 22','RBC 23','RBC 24','RBC 25','RBC 26','RBC 27');
ylabel('Standard deviation');
xlabel('Day');